# Generated by Django 5.2.14 on 2026-05-22 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsuranceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "insurance_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InsurancePackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("coverage_detail", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=0, max_digits=14)),
                (
                    "payment_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Hàng tháng"),
                            ("quarterly", "Hàng quý"),
                            ("yearly", "Hàng năm"),
                            ("one_time", "Một lần"),
                        ],
                        default="yearly",
                        max_length=10,
                    ),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(decimal_places=0, max_digits=14),
                ),
                ("duration_months", models.PositiveIntegerField(default=12)),
                ("min_age", models.PositiveIntegerField(default=18)),
                ("max_age", models.PositiveIntegerField(default=65)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang bán"),
                            ("inactive", "Ngừng bán"),
                            ("draft", "Nháp"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packages",
                        to="assurances.insurancecategory",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("registration", "Đăng ký"),
                            ("claim", "Bồi thường"),
                            ("renewal", "Gia hạn"),
                            ("cancellation", "Huỷ hợp đồng"),
                        ],
                        max_length=15,
                    ),
                ),
                ("step_order", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("duration_days", models.PositiveIntegerField(default=1)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="assurances.insurancepackage",
                    ),
                ),
            ],
            options={
                "db_table": "package_processes",
                "ordering": ["package", "process_type", "step_order"],
                "unique_together": {("package", "process_type", "step_order")},
            },
        ),
    ]
