# Generated by Django 5.2.14 on 2026-05-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assurances", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insurancecategory",
            name="icon",
        ),
    ]
